add: database
littlerock2877/java-filmorate pull request #4
Opened 2024-09-30 19:57 UTC by littlerock2877

2024-10-01 16:49 UTC, YazykovMikhail requested changes

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @NotBlank(message = "Genre name could not be empty")
Это тут не нужно, валилация делается в контролелрах, в ходящих параметразх, этот обеькт там не участвует

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    @NotBlank(message = "MPA rating name could not be empty")
Это тут не нужно, валилация делается в контролелрах, в ходящих параметразх, этот обеькт там не участвует

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +    private final UserRepository userRepository;
Репозитории между собой не общаются и не завистя друг от друга. 
Каждая репозитория занет только о своей модели и все. Ее дело работать только со своей моделью. 
Если нужно вызывать другие сервивиса/репозитории стоит их вызывать из сериса

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +        userRepository.getUserById(userId);
ты проверяешь существует ли Юзер, нет смысла заходить в репозиторий если Юзера не существует - это бизнес логика, эта проверка должна быть на уровне сервиса

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +        if (film.getGenres() == null) {
Тоже вынеси в сервис, сюда уже полностью подготовленные даныне приходят

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +        for (Genre genre : film.getGenres()) {
Можно не делать эту проверку, ведь пр исохоанении там ссылки настроены, и если id не будет, будет ошибка

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +        for (Film film : films) {
так делать не стоит, вызывать запросы в цикле - это плохо, на каждый запрос созадется соединение - эт отяжеловестаня опеарция. Тут получай фильм но без жанров, наполнение жанров будем вызывать из сервиса

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      }
public List<Film> getAll() {
		final List<Film> films = filmStorage.getAll();
		genreStorage.load(films);
		return films;
	}

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      }
А сам load будет выглядеть вот так:
```
	@Override
	public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(Film::getId).toArray());
	}

	static Genre makeGenre(ResultSet rs, int rowNum) throws SQLException {
		return new Genre(
				rs.getLong("genre_id"),
				rs.getString("name"));
	}
```

2024-10-01 16:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
А что бы получить один фильм можно сделать вот тк:

	public Film getFilmById(long id) {
		final Film film = filmStorage.get(id);
		genreStorage.load(Collections.singletonList(film));
		return film;
	}

2024-10-01 19:50 UTC, littlerock2877 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
Изменил

2024-10-01 19:50 UTC, littlerock2877 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      }
Добавил

2024-10-01 19:51 UTC, littlerock2877 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +        for (Film film : films) {
Изменил

2024-10-01 19:51 UTC, littlerock2877 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +        if (film.getGenres() == null) {
Перенес

2024-10-01 19:51 UTC, littlerock2877 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +        userRepository.getUserById(userId);
Перенес

2024-10-01 19:51 UTC, littlerock2877 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +    private final UserRepository userRepository;
Удалил

2024-10-01 19:51 UTC, littlerock2877 commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    @NotBlank(message = "MPA rating name could not be empty")
Исправил

2024-10-01 19:51 UTC, littlerock2877 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @NotBlank(message = "Genre name could not be empty")
Исправил

2024-10-01 19:53 UTC, littlerock2877 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/JdbcFilmRepository.java
> +        for (Genre genre : film.getGenres()) {
Перенес эту проверку в сервис и немного упростил ее(теперь получаем жанры только 1 раз). Без нее не работает один из тестов, падает с ошибкой "Нарушение целостности ссылок"

2024-10-02 21:04 UTC, YazykovMikhail approved these changes

2024-10-08 10:07 UTC, merged